//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recruitment
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidateWorkItem
    {
        public int CadidateWorkItemID { get; set; }
        public int CandidateID { get; set; }
        public string CompanyName { get; set; }
        public string RoleName { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string Description { get; set; }
    
        public virtual Candidate Candidate { get; set; }
    }
}
