//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recruitment
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployerUser
    {
        public int EmployerUserID { get; set; }
        public string EmployerUserFirstName { get; set; }
        public string EmployerUserLastName { get; set; }
        public string EmployerUserEmail { get; set; }
        public int EmployerID { get; set; }
    
        public virtual Employer Employer { get; set; }
    }
}
