//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recruitment
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployerDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmployerDetail()
        {
            this.Techs = new HashSet<Tech>();
        }
    
        public int EmployerDetailsID { get; set; }
        public bool Remote { get; set; }
        public bool OnSite { get; set; }
        public System.Data.Entity.Spatial.DbGeography EmployerLocation { get; set; }
        public int EmployerID { get; set; }
        public bool Contract { get; set; }
        public bool PermanentPos { get; set; }
    
        public virtual Employer Employer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tech> Techs { get; set; }
    }
}
